# Generated by Django 5.0.1 on 2024-02-03 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satker', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.satker')),
            ],
            options={
                'verbose_name': 'Satuan Kerja',
                'verbose_name_plural': 'Daftar Satuan Kerja',
                'ordering': ['nama_satker'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=True)),
                ('avatar', models.ImageField(default='images/avatar.png', upload_to='profile_avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.satker')),
            ],
            options={
                'verbose_name': 'Profile User',
                'verbose_name_plural': 'Daftar Profile User',
                'ordering': ['id'],
            },
        ),
    ]
