# Generated by Django 5.0.1 on 2024-02-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_direktorat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notelp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
