# Generated by Django 5.0.1 on 2024-02-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_reg_villages_kode_kecamatan_and_more'),
        ('users', '0005_satker_kabupaten_satker_provinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satker',
            name='kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satker', to='masters.kabupaten'),
        ),
        migrations.AlterField(
            model_name='satker',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satker', to='masters.provinsi'),
        ),
    ]
