# Generated by Django 5.0.1 on 2024-02-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Profile User', 'verbose_name_plural': 'Daftar Profile User'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
