# Generated by Django 5.0.1 on 2024-03-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_options_remove_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatkerBNNK',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('satker_id', models.BigIntegerField()),
                ('nama_satker', models.CharField(max_length=12)),
                ('kabupaten_id', models.BigIntegerField()),
                ('jumlah_profil', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users_satker_bnnk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SatkerBNNP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('satker_id', models.BigIntegerField()),
                ('nama_satker', models.CharField(max_length=12)),
                ('provinsi_id', models.BigIntegerField()),
                ('jumlah_profil', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users_satker_bnnp',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_profile', to='users.satker'),
        ),
    ]
