# Generated by Django 5.0.1 on 2024-02-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_datakawasanrawan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kawasanrawan',
            name='desa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kawasan_rawan', to='masters.desa'),
        ),
        migrations.DeleteModel(
            name='DataKawasanRawan',
        ),
    ]
