# Generated by Django 5.0.1 on 2024-02-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_kawasanrawan_desa_delete_datakawasanrawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_villages',
            name='kode_kecamatan',
        ),
        migrations.RemoveField(
            model_name='reg_regencies',
            name='kode_provinsi',
        ),
        migrations.AlterModelOptions(
            name='desa',
            options={'ordering': ['kawasan_rawan__updated_at'], 'verbose_name': 'Desa', 'verbose_name_plural': 'Daftar Desa'},
        ),
        migrations.DeleteModel(
            name='reg_district',
        ),
        migrations.DeleteModel(
            name='reg_villages',
        ),
    ]
