# Generated by Django 5.0.1 on 2024-02-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_reg_villages_kode_kecamatan_and_more'),
        ('users', '0006_alter_satker_kabupaten_alter_satker_provinsi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_provinces',
        ),
        migrations.DeleteModel(
            name='reg_regencies',
        ),
    ]
