# Generated by Django 5.0.1 on 2024-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_delete_reg_provinces_delete_reg_regencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kawasanrawan',
            name='status',
            field=models.CharField(blank=True, choices=[('bahaya', 'Bahaya'), ('waspada', 'Waspada'), ('siaga', 'Siaga'), ('aman', 'Aman'), ('kosong', 'Kosong')], max_length=15, null=True),
        ),
    ]
