# Generated by Django 5.0.1 on 2024-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_desa_geom_kabupaten_geom_kecamatan_geom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa_lengkap', models.TextField(null=True)),
                ('desa', models.CharField(max_length=100, null=True)),
                ('kecamatan', models.CharField(max_length=100, null=True)),
                ('propinsi', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'masters_view_desa',
                'managed': False,
            },
        ),
    ]
