# Generated by Django 5.0.1 on 2024-02-22 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_desaview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa', models.CharField(max_length=10, null=True)),
                ('kecamatan', models.CharField(max_length=10, null=True)),
                ('kabupaten', models.CharField(max_length=10, null=True)),
                ('provinsi', models.CharField(max_length=10, null=True)),
                ('nama_desa', models.CharField(max_length=100, null=True)),
                ('nama_kecamatan', models.CharField(max_length=100, null=True)),
                ('nama_kabupaten', models.CharField(max_length=100, null=True)),
                ('nama_provinsi', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'masters_db_desa',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='desa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
