# Generated by Django 3.2.24 on 2024-02-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_dbdesa_desa_created_at_desa_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desa',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Desa', 'verbose_name_plural': 'Daftar Desa'},
        ),
        migrations.AlterField(
            model_name='kawasanrawan',
            name='desa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kawasan_rawan', to='masters.dbdesa'),
        ),
    ]
