# Generated by Django 3.2.24 on 2024-02-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_auto_20240222_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinsiRawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=10, null=True)),
                ('nama_provinsi', models.CharField(max_length=100, null=True)),
                ('siaga', models.IntegerField()),
                ('bahaya', models.IntegerField()),
                ('waspada', models.IntegerField()),
                ('aman', models.IntegerField()),
            ],
            options={
                'db_table': 'masters_provinsi_rawan',
                'managed': False,
            },
        ),
    ]
