# Generated by Django 3.2.24 on 2024-02-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_provinsirawangeom_alter_kawasanrawan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinsi',
            name='line_geom',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='provinsi',
            name='provinsi_singkat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
