# Generated by Django 5.0.1 on 2024-02-09 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Literasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokumen', models.FileField(upload_to='upload/files/literasi')),
                ('judul', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED'), ('archived', 'ARCHIVED')], default='1', max_length=15)),
                ('kategori', models.CharField(choices=[('buku', 'Buku'), ('audio', 'Audio'), ('video', 'Video'), ('link', 'Link'), ('video_youtube', 'Video Youtube')], default='1', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literasi_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literasi_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Literasi',
                'verbose_name_plural': 'Daftar Literasi',
                'ordering': ['-updated_at'],
            },
        ),
    ]
