# Generated by Django 5.0.1 on 2024-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literasi',
            name='dokumen',
            field=models.FileField(null=True, upload_to='upload/files/literasi'),
        ),
    ]
