# Generated by Django 5.0.1 on 2024-02-11 08:12

import literasi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0002_alter_literasi_dokumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literasi',
            name='dokumen',
            field=models.FileField(null=True, upload_to='upload/files/literasi', validators=[literasi.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('buku', 'Buku'), ('audio', 'Audio'), ('video', 'Video'), ('video_youtube', 'Video Youtube')], default='buku', max_length=15),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED'), ('archived', 'ARCHIVED')], default='draft', max_length=15),
        ),
    ]
