# Generated by Django 5.0.1 on 2024-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0003_alter_literasi_dokumen_alter_literasi_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literasi',
            name='jumlah_diunduh',
            field=models.IntegerField(default=0),
        ),
    ]
