# Generated by Django 3.2.24 on 2024-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0004_literasi_jumlah_diunduh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('buku', 'Buku'), ('video', 'Video'), ('audio', 'Audio'), ('video_youtube', 'Video Youtube')], default='buku', max_length=15),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='status',
            field=models.CharField(choices=[('published', 'PUBLISHED'), ('draft', 'DRAFT'), ('archived', 'ARCHIVED')], default='draft', max_length=15),
        ),
    ]
