# Generated by Django 5.0.1 on 2024-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0005_auto_20240222_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('audio', 'Audio'), ('buku', 'Buku'), ('video_youtube', 'Video Youtube'), ('video', 'Video')], default='buku', max_length=15),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='status',
            field=models.CharField(choices=[('published', 'PUBLISHED'), ('archived', 'ARCHIVED'), ('draft', 'DRAFT')], default='draft', max_length=15),
        ),
    ]
